# Generated by Django 5.1.6 on 2025-02-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="photo",
            field=models.ImageField(upload_to="post_images", verbose_name="사진"),
        ),
    ]
