# Generated by Django 5.1.6 on 2025-02-25 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_postimage_photo"),
        ("seoul", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="place",
            field=models.ManyToManyField(related_name="posts", to="seoul.place"),
        ),
        migrations.AlterUniqueTogether(
            name="placecomplete",
            unique_together={("user", "post", "place")},
        ),
    ]
