# Generated by Django 5.1.6 on 2025-02-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, upload_to="users/profile"),
        ),
        migrations.AddField(
            model_name="user",
            name="short_description",
            field=models.TextField(blank=True),
        ),
    ]
