# Generated by Django 5.1.6 on 2025-02-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_profile_image_user_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, upload_to="profile"),
        ),
    ]
