# Generated by Django 5.1.6 on 2025-02-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seoul", "0002_alter_place_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="place_image",
            field=models.URLField(blank=True),
        ),
    ]
