# Generated by Django 5.1.6 on 2025-02-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seoul", "0003_alter_place_place_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="place_image",
            field=models.ImageField(upload_to="place_images/"),
        ),
    ]
