# Generated by Django 5.1.6 on 2025-02-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seoul", "0004_alter_place_place_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
